FROM microsoft/dotnet:2.0-sdk as builder

ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

RUN mkdir -p /root/src/extensionsample
WORKDIR /root/src/extensionsample
COPY ./**/*.csproj ./
COPY ./ExtensionSample.sln .
RUN dotnet restore ./ExtensionSample.sln

COPY . .
RUN dotnet publish ./Server/Server.csproj -c release -o published

FROM microsoft/dotnet:2.0.0-runtime
WORKDIR /root/src/extensionsample
COPY --from=builder /root/src/extensionsample/Server/published .
ENTRYPOINT ["dotnet", "Server.dll"]